services:
  app:
    image: ${DOCKERHUB_USERNAME}/oneteam-mcp:latest
    container_name: oneTeam-mcp
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      BRAVE_API_KEY: ${BRAVE_API_KEY}
    networks: [ proxy ]

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    restart: always
    depends_on: [ app ]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    networks: [ proxy ]

  certbot:
    image: certbot/certbot:v2.11.0
    container_name: certbot
    restart: always
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: /bin/sh
    command: -c "while :; do sleep 12h; certbot renew --webroot -w /var/www/certbot || true; done"
    networks: [ proxy ]

volumes:
  certbot-etc:
  certbot-www:

networks:
  proxy: {}
