spring:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          #model: claude-3-7-sonnet-20250219
          model: claude-3-haiku-20240307

    mcp:
      client:
        stdio:
          connections:
            brave-search:
              command: npx.cmd
              args:
                - "-y"
                - "@modelcontextprotocol/server-brave-search"
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}
            filesystem:
              command: npx.cmd
              args:
                - "-y"
                - "@modelcontextprotocol/server-filesystem"
                - "./"

logging:
  level:
    org.springframework.ai.mcp: DEBUG
