spring:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          #model: claude-3-7-sonnet-20250219
          model: claude-3-haiku-20240307

    mcp:
      client:
        stdio:
          connections:
            brave-search:
              command: /usr/local/bin/mcp-server-brave-search
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}

            filesystem:
              command: /usr/local/bin/mcp-server-filesystem
              args:
                - "./"          # 작업 루트 지정 (필요 시 절대경로로)

            chanmcp:
              command: /usr/local/bin/smithery
              args:
                - run
                - "@hwruchan/chanmcp"
                - "--key"
                - ${SEQUENTIAL_ST_KEY}

#        sse:
#          connections:
#            author-tools-server:
#              url: http://localhost:8081

logging:
  level:
    org.springframework.ai.mcp: DEBUG
