spring:
  ai:
    anthropic:
      api-key: ${ANTHROPIC_API_KEY}
      chat:
        options:
          #model: claude-3-7-sonnet-20250219
          model: claude-3-haiku-20240307

    mcp:
      client:
        request-timeout: 180s
        stdio:
          connections:
            brave-search:
              command: npx.cmd
              args: [ "-y", "@modelcontextprotocol/server-brave-search" ]
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}
            filesystem:
              command: npx.cmd
              args: ["-y", "@modelcontextprotocol/server-filesystem", "./"]
            chanmcp:
              command: npx.cmd
              args: [ "-y", "@smithery/cli@latest", "run", "@hwruchan/chanmcp", "--key", "${SEQUENTIAL_ST_KEY}" ]

#        sse:
#          connections:
#            author-tools-server:
#              url: http://localhost:8081

logging:
  level:
    org.springframework.ai.mcp: DEBUG
