spring:
  ai:
    openai:
    #anthropic:
      #api-key: ${ANTHROPIC_API_KEY}
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
          #model: claude-3-7-sonnet-20250219
          #model: claude-3-haiku-20240307

    mcp:
      client:
        initialized: true
        request-timeout: 60s
        toolcallback:
          enabled: false
        stdio:
          connections:
            brave-search:
              command: npx
              args: [ "-y", "@modelcontextprotocol/server-brave-search" ]
              env:
                BRAVE_API_KEY: ${BRAVE_API_KEY}
            chanmcp:
              command: npx
              args: [ "-y", "@smithery/cli@latest", "run", "@hwruchan/chanmcp", "--key", "${SEQUENTIAL_ST_KEY}" ]


logging:
  level:
    org.springframework.ai.mcp: DEBUG
    io: WARN
